### ISSUE TITLE
TestCases:

### ISSUE THREAD

**Issue by AvaruusAnkka** [AkiManni/voltti#16]
Lisää sitä mukaa kun työstät ja testaat ominaisuutta:

- [x] [Test Case #1](https://oamk.sharepoint.com/teams/TVTDINRyhm21doc-kansio/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FTVTDINRyhm21doc%2Dkansio%2FShared%20Documents%2FGroup%2021%20%2D%20TestCase%20%231%2Epdf&parent=%2Fteams%2FTVTDINRyhm21doc%2Dkansio%2FShared%20Documents) Manager orderOverview - ( 21.11.2021 - 10.12.2021 ) - <b>(Aki)</b>

- [x] [Test Case #2](https://oamk.sharepoint.com/:b:/r/teams/TVTDINRyhm21doc-kansio/Shared%20Documents/Group%2021%20-%20TestCase%20%232.pdf?csf=1&web=1&e=SgsQPr) User login - ( 12.12.2021 ) <b>(Janne)</b> 

- [x] [Test Case #3](https://oamk.sharepoint.com/:b:/r/teams/TVTDINRyhm21doc-kansio/Shared%20Documents/Group%2021%20-%20TestCase%20%233.pdf?csf=1&web=1&e=wbJSjH) User Registeration - ( 12.12.2021 ) <b>(Janne)</b>

- [x] [Test Case #4, #5, #6](https://oamk.sharepoint.com/:x:/t/TVTDINRyhm21doc-kansio/EUYUIsthO-1Kr2c1qRBayFoBOKrGIsl_z7OBFSmpC-LQwA?e=8fwTMy) Backend - ( 14.12.2021 ) <b>(Andy)</b>
